### ISSUE TITLE
Missing R kernel in "no matplotlib" container

### ISSUE THREAD

**Issue by mcapuccini** [phnmnl/container-jupyter#5]
The "no matplotlib" container misses the R kernel for Jupyter.

![screen shot 2017-02-25 at 16 22 04](https://cloud.githubusercontent.com/assets/1671397/23332298/9ad487f8-fb77-11e6-91b4-1263660d0fc0.png)

**Comment by pcm32** [comment]
Thanks for raising the issue, is this now fixed in the no-matplotlib branch, with [this commit](https://github.com/phnmnl/container-jupyter/commit/3d34bd6db3ed2e3278609ec7cea34ba4506f2c7f). I have pushed it to dockerhub as well.
