### ISSUE TITLE
R Kernel does not work

### ISSUE THREAD

**Issue by mcapuccini** [phnmnl/container-jupyter#6]
Kernel dies when trying to run a command:

![screen shot 2017-02-27 at 13 12 56](https://cloud.githubusercontent.com/assets/1671397/23360971/84dcafb6-fcee-11e6-9f79-f836a6920d6f.png)

To replicate: New > R > Type sessionInfo() in a cell > Run

**Comment by pcm32** [comment]
Thanks for reporting it @mcapuccini ! I sorted this out now with commits after [f9cffa62f4043eb](https://github.com/phnmnl/container-jupyter/commit/f9cffa62f4043eb8d499abf1d22004708e9a857f).
